version: "1.1"
services:
  redis-node-1:
    image: redis:6.0-alpine
    container_name: redis-node-1
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7001:6379"
    volumes:
      - redis-node-1-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.10
        
  redis-node-2:
    image: redis:6.0-alpine
    container_name: redis-node-2
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes  --slaveof redis-node-1 7001
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7002:6379"
    volumes:
      - redis-node-2-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    depends_on:
      - redis-node-1
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2      
        
  redis-node-3:
    image: redis:6.0-alpine
    container_name: redis-node-3
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes  --slaveof redis-node-1 7001
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7003:6379"
    volumes:
      - redis-node-3-data:/data   
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    depends_on:
      - redis-node-1
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.3     
         
  redis-node-4:
    image: redis:6.0-alpine
    container_name: redis-node-4
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes  --slaveof redis-node-1 7001
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7004:6379"
    volumes:
      - redis-node-4-data:/data   
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    depends_on:
      - redis-node-1
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.4  
        
  redis-node-5:
    image: redis:6.0-alpine
    container_name: redis-node-5
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes  --slaveof redis-node-1 7001
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7005:6379"
    volumes:
      - redis-node-5-data:/data   
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    depends_on:
      - redis-node-1
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.5  
        
  redis-node-6:
    image: redis:6.0-alpine
    container_name: redis-node-6
#    environment:
#      CLUSTER_NODES: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
#    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/etc/redis/nodes.conf", "--cluster-node-timeout", "5000"]
#    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes  --slaveof redis-node-1 7001
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "7006:6379"
    volumes:
      - redis-node-6-data:/data   
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf      
    depends_on:
      - redis-node-1
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.6                  
         
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_web
    environment:
      REDIS_HOSTS: "local:redis-node-1:6379,local:redis-node-2:6379,local:redis-node-3:6379,local:redis-node-4:6379,local:redis-node-5:6379,local:redis-node-6:6379"
    ports:
      - "5000:8081"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - cluster_initiator
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.9
        
  cluster_initiator:
    container_name: cluster_initiator
    build:
      context: redis
      dockerfile: Dockerfile
    volumes:
      - cluster_initiator-data:/data        
    tty: true
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6      
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.8
          
volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:    
  cluster_initiator-data:          
  
networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16  