spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
             
             authorization-uri: https://gitlab.com/oauth/authorize
             token-uri: https://gitlab.com/oauth/token
             #user-info-uri: https://gitlab.com/oauth/userinfo
             #user-info-uri: https://gitlab.com/api/v4/user
             jwk-set-uri: https://gitlab.com/oauth/discovery/keys
             #suser-name-attribute: username
        registration:
          github:
            client-id: Iv1.c9e08cc5d5bbc466
            client-secret: 6b21b92e403a9add55aa7ed43a02c2724aa88b25
          gitlab:
            client-authentication-method: client_secret_post
            provider: gitlab
            client-id: d48c1b9e5dc524c1a7a0399977af56cea7804af375181e7c052905b471daefc1
            client-secret: f33d50c58efe752ecbcb3526ac38023ef4841c9f1b79e64ff828fb248fc7b4b8
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
            scope:
            #- read_user
            - openid
            - profile
          google:
            client-id: google-id
            client-secret: google-secret-here
          facebook:
            client-id: facebook-id
            client-secret: facebook-secret-here            
            
logging:
  level:
    org:
      springframework:
        security: DEBUG
            